### PR TITLE
Replace explicit warning levels by named constants

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by ianhinder** [comment]
The code looks good, but the "Merge branch master" commit seems to contain changes not related to merging.  I would like to avoid merge commits unless they carry useful info, e.g. from a long-lived branch, since they clutter the history.  Please could you reword the commit message to reflect the content, and rebase off current master? Thanks!

**Comment by eschnett** [comment]
Can you point to some of the unrelated changes? I don't see any.

**Comment by ianhinder** [comment]
If I click on the "Merge branch master" commit above, I see KEYWORD -> CCTK_KEYWORD, for example.

**Comment by eschnett** [comment]
Yes, of course. These are the changes from the master that were merged in.

**Pull request closed without merging**
